### PR TITLE
Implement Encode for tuples with up-to 16 elements.

### PR DESCRIPTION
**Pull request by gz**
This makes it match the implementation of Decode which already supports up to 16 fields.

### CODE REVIEW

**Comment by VictorKoenders** [comment]
I forget why this isn't a macro as well, but I see no reason to block this PR on that

**Review by VictorKoenders — APPROVED** [review]
Thanks!

**Comment by VictorKoenders** [comment]
For your vmware PR; the next release candidate milestone is tracked here: https://github.com/bincode-org/bincode/milestone/6

**Comment by gz** [comment]
> I forget why this isn't a macro as well, but I see no reason to block this PR on that

I tried to improve that, but struggled with generating code that uses .0, .1, .2 etc. when trying to access the tuple members A, B, C etc. for calling encode. So eventually I gave up.

For future reference: Maybe the right way is to unpack the tuple with something like `let $tuple_name($($element),*) = self;`

**Pull request merged**
